version: '3.1'

services:
  db:
    image: postgres:alpine
    container_name: geolocation-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - geolocation-db:/var/lib/postgresql/data
    networks:
      - base
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: geolocation

  pgadmin:
    image: dpage/pgadmin4
    container_name: geolocation-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@docker.com'
      PGADMIN_DEFAULT_PASSWORD: 'docker'
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - base

volumes:
  geolocation-db:

networks:
  base:
